### ISSUE TITLE
Spurious `[WARN]sysfs create failed` warning

### ISSUE THREAD

**Issue by benzea** [intel/thermal_daemon#239]
```
(gdb) bt
#0  csys_fs::create() (this=this@entry=0x4a5360) at /usr/include/c++/10/bits/basic_string.h:2299
#1  0x000000000044b4a8 in cthd_gen_sysfs_cdev::update() (this=0x4a5350) at src/thd_cdev_gen_sysfs.cpp:34
#2  0x00000000004290f1 in cthd_engine_default::add_replace_cdev(cooling_dev_t*) (this=0x4a2b00, config=0x481900 <cpu_def_cooling_devices+160>)
    at src/thd_engine_default.cpp:608
#3  0x000000000042c82f in cthd_engine_default::read_cooling_devices() (this=0x4a2b00) at src/thd_engine_default.cpp:708
#4  0x00000000004206f8 in cthd_engine::thd_engine_start(bool) (this=this@entry=0x4a2b00, ignore_cpuid_check=ignore_cpuid_check@entry=false) at src/thd_engine.cpp:252
#5  0x00000000004287cf in thd_engine_create_default_engine(bool, bool, char const*)
    (ignore_cpuid_check=<optimized out>, exclusive_control=<optimized out>, conf_file=0x0) at src/thd_engine_default.cpp:785
#6  0x0000000000418ff7 in main(int, char**) (argc=<optimized out>, argv=<optimized out>) at src/main.cpp:325
(gdb) up
#1  0x000000000044b4a8 in cthd_gen_sysfs_cdev::update (this=0x4a5350) at src/thd_cdev_gen_sysfs.cpp:34
34			int ret = cdev_sysfs.create();
(gdb) 
#2  0x00000000004290f1 in cthd_engine_default::add_replace_cdev (this=0x4a2b00, config=0x481900 <cpu_def_cooling_devices+160>) at src/thd_engine_default.cpp:608
608			if (cdev->update() != THD_SUCCESS) {
(gdb) print cdev.cdev_sysfs 
$3 = {base_path = ""}
```

This seems to come from `cthd_engine_default::add_replace_cdev` which will happily call `cdev = new cthd_gen_sysfs_cdev(current_cdev_index, config->path_str);` with `path_str` being an empty string.

I guess that might be wrong in the first place, but the code looks very much intentional, explicitly taking that branch when the string *is* empty.

**Comment by spandruvada** [comment]
Fixed warning for empty path string.
